# Reflex3 is the new offensive and new defensive
[group('submission'), parallel]
submission-exp: ReflexV3-vs-MinimaxV2 ReflexV3-vs-baseline MinimaxV2-vs-baseline

[group('submission')]
ReflexV3-vs-MinimaxV2:
    {{python_interpreter}} {{default_exp_args}} \
    -u ReflexV3-vs-MinimaxV2 \
    -r {{research_teams_dir}}MinimaxV2.py \
    --red-name MinimaxV2 \
    -b {{research_teams_dir}}submission.py \
    --blue-name ReflexV3

[group('submission')]
ReflexV3-vs-baseline:
   {{python_interpreter}} {{default_exp_args}} \
   -u ReflexV3-vs-baseline \
   --red-name baseline \
   -b {{research_teams_dir}}submission.py \
   --blue-name ReflexV3

[group('submission')]
MinimaxV2-vs-baseline:
    {{python_interpreter}} {{default_exp_args}} \
    -u MinimaxV2-vs-baseline \
    --red-name baseline \
    -b {{research_teams_dir}}MinimaxV2.py \
    --blue-name MinimaxV2


