from pathlib import Path
import pandas as pd
import json
import time


class GameAnalysis:
    """
    This class provides an object that stores useful game information obtained from the json files generated by the --record option in the capture.py script.
    """

    def __init__(self, json_path: Path):
        self.json_path = json_path
        self.experiment_name = json_path.parent.parent.name.removeprefix('contest_')
        __filetime = json_path.stat().st_ctime
        self.experiment_time = time.ctime(__filetime)

        with open(self.json_path, 'r') as file:
            json_object = json.load(file)
            self.json_object = json_object

        team_stats = json_object['teams_stats']
        keys = list(team_stats.keys())
        blue_stats = team_stats[keys[0]]
        red_stats = team_stats[keys[1]]

        self.team_stats_dataframe = pd.DataFrame(
            {'blue_stats': blue_stats,
             'red_stats': red_stats}
        ).T

        games_data = json_object['games']
        self.games_dataframe = pd.DataFrame(games_data).rename(columns={
                0: 'team_1',
                1: 'team_2',
                2: 'layout',
                3: 'score',
                4: 'winner',
                5: 'time_taken',
                6: 'match_number'
            })
