from pathlib import Path
import pandas as pd
import json
import time
import seaborn as sns
import numpy as np


class GameAnalysis:
    """
    This class provides an object that stores useful game information obtained from the JSON files generated by the --record option in the capture.py script.
    """
    #TODO: add exceptions
    #       - only accept json
    #       - check that path is absolute

    def __init__(self, json_path: Path):
        self.json_path = json_path.resolve()
        # This should equal to the CONTEST_NAME option (-u flag in capture.py)
        self.experiment_name = json_path.parent.parent.name.removeprefix('contest_')
        __filetime = json_path.stat().st_ctime
        # This returns when the time and date when the experiment was run. See dataframes for duration
        self.experiment_time = time.ctime(__filetime)

        with open(self.json_path, 'r') as file:
            json_object = json.load(file)
            self.json_object = json_object

        # helper variables to wrangle the JSON object
        team_stats = json_object['teams_stats']
        keys = list(team_stats.keys())
        team1_stats = team_stats[keys[0]]
        team2_stats = team_stats[keys[1]]

        # dataframe that roughly corresponds to the raw 'teamstats' field in the JSON object
        # Note: index is currently the team name. An extra 'team' column with team-name as value has been added for convenience
        # team-name should correspond to the --red/blue-name flags in capture.py
        self.team_stats_dataframe = pd.DataFrame(
            {keys[0]: team1_stats,
             keys[1]: team2_stats}
        ).T.rename(columns={
            0: 'points_percentage',
            1: 'points',
            2: 'wins',
            3: 'draws',
            4: 'losses',
            5: 'errors',
            6: 'sum_score'
        }).assign(team = [keys[0], keys[1]])

        # dataframe that roughly corresponds to the "games" field in the JSON object
        # Note: the 'score' in the JSON object slightly differs from the summary you get from the .log file!
            # currently only positive scores are shown in (conversely, log summary also shows negative score values)
        games_data = json_object['games']
        self.games_dataframe = pd.DataFrame(games_data).rename(columns={
                0: 'team_1',
                1: 'team_2',
                2: 'layout',
                3: 'score',
                4: 'winner',
                5: 'time_taken',
                6: 'match_number'
            })


    def generate_winplot(self):
        reshaped_df = self.team_stats_dataframe[['team', 'wins', 'draws']].melt(id_vars=['team'], var_name='outcome', value_name='count')

        # make a "draws" team as this score is the same for both teams and could be visualized only once
        reshaped_df['team'] = np.where(reshaped_df['outcome'] == 'draws', 'draws', reshaped_df['team'])

        # omit final row as there are two draws teams
        reshaped_df.head(len(reshaped_df) - 1)

        plot = (sns.barplot(
            data=reshaped_df,
            x='team',
            y='count',
            hue='team',
            palette='muted')
            .set(title=f"{self.experiment_name}".replace("VS", " VS ")))

        return plot